from __future__ import annotations

import argparse
from pathlib import Path

from src.datamind.selected_analysis import (
    build_template_analysis,
    load_selected_tables,
    write_template_analysis_report,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Analyze selective 11-table fund data")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("output/url_selective_11tables_missingb_v2.xlsx"),
        help="Input Excel path generated by selective URL mode (11 sheets)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/analysis_template_report.xlsx"),
        help="Output analysis workbook path",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    tables = load_selected_tables(args.input)
    analysis_tables = build_template_analysis(tables)
    write_template_analysis_report(args.output, analysis_tables)
    print(f"Analysis done: {args.output}")


if __name__ == "__main__":
    main()
